# Generated by Django 4.2.7 on 2025-06-30 05:00

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de identificación (PDF)'),
        ),
    ]
