# Generated by Django 4.2.7 on 2025-06-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatviaje_mensajechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatviaje',
            name='actualizado_en',
        ),
    ]
